"""compare_solvers tool for OR-Intern Phase 2.

Runs multiple solvers on the same model and compares performance:
solve time, objective value, gap, status. Supports HiGHS/SCIP/GLPK.
"""

import asyncio
import logging
import re
import sys
import tempfile
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_COMPARE_SCRIPT = '''\
"""Solver comparison — auto-generated by OR-Intern."""
import sys, time as _time
sys.path.insert(0, r"{model_dir}")
from pyomo.environ import *

{model_code}

solvers = [{solver_list}]
results = []

for s in solvers:
    try:
        solver = SolverFactory(s)
        if not solver.available():
            results.append((s, "UNAVAILABLE", 0, 0, ""))
            continue
        t0 = _time.monotonic()
        result = solver.solve(model, tee=False)
        elapsed = _time.monotonic() - t0
        
        try:
            obj_val = value(model.obj)
        except:
            obj_val = -1
        
        results.append((
            s,
            str(result.solver.termination_condition),
            elapsed,
            obj_val,
            str(result.solver.status),
        ))
    except Exception as e:
        results.append((s, "ERROR", 0, 0, str(e)[:100]))

print("COMPARISON_START")
for s, status, elapsed, obj_val, solver_status in results:
    print(f"{{s}}|{{status}}|{{elapsed:.3f}}|{{obj_val}}|{{solver_status}}")
print("COMPARISON_END")
'''


# ── Tool spec and handler ──

COMPARE_SOLVERS_TOOL_SPEC = {
    "name": "compare_solvers",
    "description": (
        "Compare multiple solvers on the same optimization model. "
        "Runs solvers in sequence and reports: solver name, status, solve time, "
        "objective value. Use to find the best solver for a given problem."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "model_path": {
                "type": "string",
                "description": "Path to the Pyomo model Python file",
            },
            "solvers": {
                "type": "string",
                "description": "Comma-separated solver list (default: highs,glpk)",
                "default": "highs",
            },
        },
        "required": ["model_path"],
    },
}


async def compare_solvers_handler(args: dict[str, Any]) -> tuple[str, bool]:
    """Handler for compare_solvers tool."""
    model_path = args.get("model_path", "")
    solver_list_str = args.get("solvers", "highs")

    if not model_path:
        return "Error: No model path provided", True

    model_path = Path(model_path)
    if not model_path.exists():
        return f"Error: Model file not found: {model_path}", True

    model_code = model_path.read_text(encoding="utf-8")
    solvers = [s.strip() for s in solver_list_str.split(",") if s.strip()]
    solver_list_py = ", ".join(f'"{s}"' for s in solvers)

    script = _COMPARE_SCRIPT.format(
        model_dir=model_path.parent,
        model_code=model_code,
        solver_list=solver_list_py,
    )

    tmpdir = Path(tempfile.gettempdir()) / "or-intern"
    tmpdir.mkdir(exist_ok=True)
    script_path = tmpdir / "compare.py"
    script_path.write_text(script, encoding="utf-8")

    try:
        process = await asyncio.create_subprocess_exec(
            sys.executable, str(script_path),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(model_path.parent),
        )
        stdout, stderr = await asyncio.wait_for(
            process.communicate(), timeout=120
        )
        output = stdout.decode("utf-8", errors="replace")
        stderr_str = stderr.decode("utf-8", errors="replace")

        # Check for subprocess failure
        if process.returncode != 0:
            error_msg = stderr_str[-2000:] if stderr_str else "(no stderr)"
            return f"## Solver Comparison Failed\n\n**Exit code**: {process.returncode}\n\n**Error**:\n```\n{error_msg}\n```", True

        # Parse comparison results
        section = output.split("COMPARISON_START")[-1]
        section = section.split("COMPARISON_END")[0]

        report = ["## Solver Comparison\n"]
        report.append("| Solver | Status | Time (s) | Objective | Solver Status |")
        report.append("|--------|--------|----------|-----------|---------------|")

        for line in section.strip().split("\n"):
            if not line.strip():
                continue
            parts = line.split("|")
            if len(parts) >= 5:
                solver = parts[0]
                status = parts[1]
                elapsed = parts[2]
                obj = parts[3]

                # Color code status
                status_icon = "[OK]" if "optimal" in status.lower() else f"[{status}]" if status == "UNAVAILABLE" else f"[{status}]"

                try:
                    obj_float = float(obj)
                    obj_str = f"{obj_float:.4f}"
                except ValueError:
                    obj_str = obj

                try:
                    time_float = float(elapsed)
                    time_str = f"{time_float:.3f}"
                except ValueError:
                    time_str = elapsed

                report.append(
                    f"| {solver} | {status_icon} | {time_str} | {obj_str} | {status} |"
                )

        # Find best
        best_solver = None
        best_time = float("inf")
        for line in section.strip().split("\n"):
            if not line.strip():
                continue
            parts = line.split("|")
            if len(parts) >= 5 and "optimal" in parts[1].lower():
                try:
                    t = float(parts[2])
                    if t < best_time:
                        best_time = t
                        best_solver = parts[0]
                except ValueError:
                    pass

        if best_solver:
            report.append(f"\n**Fastest**: {best_solver} ({best_time:.3f}s)")

        return "\n".join(report), False

    except asyncio.TimeoutError:
        return "Error: Solver comparison timed out", True
    except Exception as e:
        return f"Error: {e}", True
