"""report_generator tool for OR-Intern Phase 2.

Generates formatted Markdown reports from optimization results,
including problem description, model details, solution summary,
sensitivity analysis, and visualizations.
"""

import logging
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_REPORT_TEMPLATE = """\
# OR-Intern Optimization Report

**Generated**: {timestamp}
**Solver**: {solver}
**Status**: {status}

---

## Problem Description

{problem_description}

## Model Summary

- **Type**: {problem_type}
- **Variables**: {num_variables}
- **Constraints**: {num_constraints}

## Solution

**Objective Value**: {objective}

### Variable Values

{var_table}

{constraint_table}

{sensitivity_section}

{visualization_section}

---

*Report generated by OR-Intern v0.1.0*
"""


def _format_var_table(variables: dict) -> str:
    """Format variables as markdown table."""
    lines = ["| Variable | Value |", "|----------|-------|"]
    for name, val in sorted(variables.items()):
        lines.append(f"| {name} | {val:.4f} |")
    return "\n".join(lines)


def _format_constraint_table(constraints: dict) -> str:
    """Format constraint utilization as markdown table."""
    if not constraints:
        return ""
    lines = ["## Constraint Analysis", "",
             "| Constraint | Shadow Price |", "|------------|-------------|"]
    for name, dual in sorted(constraints.items()):
        lines.append(f"| {name} | {dual:.4f} |")
    return "\n".join(lines)


# ── Tool spec and handler ──

REPORT_GENERATOR_TOOL_SPEC = {
    "name": "report_generator",
    "description": (
        "Generate a formatted Markdown report from optimization results. "
        "Includes problem description, model details, solution summary, "
        "sensitivity analysis, and visualizations. Output: Markdown file path."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "problem_description": {
                "type": "string",
                "description": "Original problem description",
            },
            "problem_type": {
                "type": "string",
                "description": "Problem type: LP, MIP, NLP, etc.",
                "default": "LP",
            },
            "objective": {
                "type": "number",
                "description": "Objective function value",
            },
            "variables": {
                "type": "object",
                "description": 'Variable values, e.g. {"x": 10.0, "y": 0.0}',
            },
            "constraints": {
                "type": "object",
                "description": 'Constraint dual values, e.g. {"c1": 3.0}',
            },
            "solver": {
                "type": "string",
                "description": "Solver used",
                "default": "HiGHS",
            },
            "status": {
                "type": "string",
                "description": "Solution status",
                "default": "OPTIMAL",
            },
            "chart_paths": {
                "type": "array",
                "description": "List of chart file paths to include",
            },
        },
    },
}


async def report_generator_handler(args: dict[str, Any]) -> tuple[str, bool]:
    """Handler for report_generator tool."""
    problem_desc = args.get("problem_description", "Optimization problem")
    problem_type = args.get("problem_type", "LP")
    objective = args.get("objective", "N/A")
    variables = args.get("variables", {})
    constraints = args.get("constraints", {})
    solver = args.get("solver", "HiGHS")
    status = args.get("status", "OPTIMAL")
    chart_paths = args.get("chart_paths", [])

    # Build sections
    var_table = _format_var_table(variables)
    constraint_table = _format_constraint_table(constraints)

    sensitivity_section = ""
    if constraints:
        sensitivity_section = "## Sensitivity Analysis\n\n" + constraint_table

    visualization_section = ""
    if chart_paths:
        visualization_section = "## Visualizations\n\n"
        for path in chart_paths:
            visualization_section += f"![Chart]({path})\n\n"

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = _REPORT_TEMPLATE.format(
        timestamp=timestamp,
        solver=solver,
        status=status,
        problem_description=problem_desc,
        problem_type=problem_type,
        num_variables=len(variables),
        num_constraints=len(constraints),
        objective=objective,
        var_table=var_table,
        constraint_table=constraint_table,
        sensitivity_section=sensitivity_section,
        visualization_section=visualization_section,
    )

    # Write to file
    tmpdir = Path(tempfile.gettempdir()) / "or-intern" / "reports"
    tmpdir.mkdir(parents=True, exist_ok=True)
    report_path = tmpdir / f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    report_path.write_text(report, encoding="utf-8")

    result = (
        f"## Report Generated\n\n"
        f"**Report file**: {report_path}\n"
        f"**Length**: {len(report)} chars\n"
        f"**Sections**: Problem, Model, Solution, Sensitivity, Visualizations\n\n"
        f"Use `read` to view the full report."
    )

    return result, False
