"""report_generator tool for OR-Intern Phase 2.

Generates formatted Markdown reports from optimization results,
including problem description, model details, solution summary,
sensitivity analysis, and visualizations.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from agent.tools._output_dir import get_workspace_dir, suggest_filename, record_file

logger = logging.getLogger(__name__)

_REPORT_TEMPLATE = """\
# {title}

**Generated**: {timestamp}
**Solver**: {solver}
**Status**: {status}

---

## Problem Description

{problem_description}

## Model Summary

- **Type**: {problem_type}
- **Variables**: {num_variables}
- **Constraints**: {num_constraints}

## Solution

**Objective Value**: {objective}

### Variable Values

{var_table}

{constraint_table}

{sensitivity_section}

{visualization_section}

{custom_sections}

---

*Report generated by OR-Intern v0.5.0*
"""

_LATEX_TEMPLATE = r"""
\documentclass[11pt]{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage{{amsmath,amssymb}}
\usepackage{{booktabs}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}
\usepackage{{geometry}}
\geometry{{a4paper, margin=1in}}

\title{{OR-Intern Optimization Report}}
\author{{Generated by OR-Intern v0.5.0}}
\date{{{timestamp}}}

\begin{{document}}
\maketitle

\section{{Problem Description}}
{problem_description}

\section{{Model Summary}}
\begin{{itemize}}
  \item \textbf{{Type}}: {problem_type}
  \item \textbf{{Variables}}: {num_variables}
  \item \textbf{{Constraints}}: {num_constraints}
\end{{itemize}}

\section{{Solution}}
\textbf{{Objective Value}}: {objective}

\subsection{{Variable Values}}
{var_table_latex}

{sensitivity_section_latex}

{visualization_section_latex}

\section{{Solver Information}}
\begin{{itemize}}
  \item \textbf{{Solver}}: {solver}
  \item \textbf{{Status}}: {status}
\end{{itemize}}

\end{{document}}
"""


def _format_var_table(variables: dict) -> str:
    """Format variables as markdown table."""
    lines = ["| Variable | Value |", "|----------|-------|"]
    for name, val in sorted(variables.items()):
        if isinstance(val, (int, float)):
            lines.append(f"| {name} | {val:.4f} |")
        else:
            lines.append(f"| {name} | {val} |")
    return "\n".join(lines)


def _format_var_table_latex(variables: dict) -> str:
    """Format variables as LaTeX table."""
    lines = [
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"Variable & Value \\",
        r"\midrule",
    ]
    for name, val in sorted(variables.items()):
        if isinstance(val, (int, float)):
            lines.append(f"{name} & {val:.4f} \\\\")
        else:
            lines.append(f"{name} & {val} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


def _format_constraint_table(constraints: dict) -> str:
    """Format constraint utilization as markdown table."""
    if not constraints:
        return ""
    lines = ["## Constraint Analysis", "",
             "| Constraint | Shadow Price |", "|------------|-------------|"]
    for name, dual in sorted(constraints.items()):
        if isinstance(dual, (int, float)):
            lines.append(f"| {name} | {dual:.4f} |")
        else:
            lines.append(f"| {name} | {dual} |")
    return "\n".join(lines)


def _format_constraint_table_latex(constraints: dict) -> str:
    """Format constraint utilization as LaTeX table."""
    if not constraints:
        return ""
    lines = [
        r"\subsection{Sensitivity Analysis}",
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"Constraint & Shadow Price \\",
        r"\midrule",
    ]
    for name, dual in sorted(constraints.items()):
        if isinstance(dual, (int, float)):
            lines.append(f"{name} & {dual:.4f} \\\\")
        else:
            lines.append(f"{name} & {dual} \\\\")
    lines.extend([r"\bottomrule", r"\end{tabular}"])
    return "\n".join(lines)


# ── Tool spec and handler ──

REPORT_GENERATOR_TOOL_SPEC = {
    "name": "report_generator",
    "description": (
        "Generate a formatted report from optimization results. "
        "Supports Markdown and LaTeX formats. "
        "Includes problem description, model details, solution summary, "
        "sensitivity analysis, visualizations, and custom sections."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "title": {
                "type": "string",
                "description": "Report title",
                "default": "OR-Intern Optimization Report",
            },
            "problem_description": {
                "type": "string",
                "description": "Original problem description",
            },
            "problem_type": {
                "type": "string",
                "description": "Problem type: LP, MIP, NLP, etc.",
                "default": "LP",
            },
            "objective": {
                "type": "number",
                "description": "Objective function value",
            },
            "variables": {
                "type": "object",
                "description": 'Variable values, e.g. {"x": 10.0, "y": 0.0}',
            },
            "constraints": {
                "type": "object",
                "description": 'Constraint dual values, e.g. {"c1": 3.0}',
            },
            "solver": {
                "type": "string",
                "description": "Solver used",
                "default": "HiGHS",
            },
            "status": {
                "type": "string",
                "description": "Solution status",
                "default": "OPTIMAL",
            },
            "chart_paths": {
                "type": "array",
                "description": "List of chart file paths to include",
            },
            "custom_sections": {
                "type": "array",
                "description": 'Custom sections to add: [{"title": "Section Name", "content": "Markdown content"}]',
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "content": {"type": "string"},
                    },
                },
            },
            "format": {
                "type": "string",
                "enum": ["markdown", "latex"],
                "description": "Output format: markdown or latex",
                "default": "markdown",
            },
            "filename": {
                "type": "string",
                "description": "Output filename",
            },
        },
    },
}


async def report_generator_handler(args: dict[str, Any], session=None) -> tuple[str, bool]:
    """Handler for report_generator tool."""
    try:
        title = args.get("title", "OR-Intern Optimization Report")
        problem_desc = args.get("problem_description", "Optimization problem")
        problem_type = args.get("problem_type", "LP")
        objective = args.get("objective", "N/A")
        variables = args.get("variables", {})
        constraints = args.get("constraints", {})
        solver = args.get("solver", "HiGHS")
        status = args.get("status", "OPTIMAL")
        chart_paths = args.get("chart_paths", [])
        custom_sections = args.get("custom_sections", [])
        output_format = args.get("format", "markdown")
        filename = args.get("filename", "")

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        workspace = get_workspace_dir(session)

        # Build custom sections content
        custom_sections_content = ""
        if custom_sections:
            for section in custom_sections:
                section_title = section.get("title", "")
                section_content = section.get("content", "")
                if section_title:
                    custom_sections_content += f"\n## {section_title}\n\n"
                if section_content:
                    custom_sections_content += section_content + "\n\n"

        if output_format == "latex":
            var_table_latex = _format_var_table_latex(variables)
            sensitivity_section_latex = _format_constraint_table_latex(constraints)

            visualization_section_latex = ""
            if chart_paths:
                for path in chart_paths:
                    visualization_section_latex += f"\\includegraphics[width=0.8\\textwidth]{{{path}}}\n\n"

            report = _LATEX_TEMPLATE.format(
                timestamp=timestamp,
                solver=solver,
                status=status,
                problem_description=problem_desc.replace("\n", "\\\\"),
                problem_type=problem_type,
                num_variables=len(variables),
                num_constraints=len(constraints),
                objective=objective,
                var_table_latex=var_table_latex,
                sensitivity_section_latex=sensitivity_section_latex,
                visualization_section_latex=visualization_section_latex,
            )

            if filename:
                report_path = workspace / filename
            else:
                report_path = workspace / suggest_filename(workspace, "report", ".tex")
            report_path.write_text(report, encoding="utf-8")
            record_file(workspace, report_path.name, file_type="report",
                        tool="report_generator", note=f"LaTeX: {status}")

            result = (
                f"## LaTeX Report Generated\n\n"
                f"**Report file**: {report_path}\n"
                f"**Length**: {len(report)} chars\n\n"
                f"To compile: `pdflatex {report_path}`"
            )
        else:
            var_table = _format_var_table(variables)
            constraint_table = _format_constraint_table(constraints)

            sensitivity_section = ""
            if constraints:
                sensitivity_section = "## Sensitivity Analysis\n\n" + constraint_table

            visualization_section = ""
            if chart_paths:
                visualization_section = "## Visualizations\n\n"
                for path in chart_paths:
                    visualization_section += f"![Chart]({path})\n\n"

            report = _REPORT_TEMPLATE.format(
                title=title,
                timestamp=timestamp,
                solver=solver,
                status=status,
                problem_description=problem_desc,
                problem_type=problem_type,
                num_variables=len(variables),
                num_constraints=len(constraints),
                objective=objective,
                var_table=var_table,
                constraint_table=constraint_table,
                sensitivity_section=sensitivity_section,
                visualization_section=visualization_section,
                custom_sections=custom_sections_content,
            )

            if filename:
                report_path = workspace / filename
            else:
                report_path = workspace / suggest_filename(workspace, "report", ".md")
            report_path.write_text(report, encoding="utf-8")
            record_file(workspace, report_path.name, file_type="report",
                        tool="report_generator", note=f"Markdown: {status}, obj={objective}")

            result = (
                f"## Report Generated\n\n"
                f"**Report file**: {report_path}\n"
                f"**Length**: {len(report)} chars\n"
                f"**Sections**: Problem, Model, Solution, Sensitivity, Visualizations\n\n"
                f"Use `read` to view the full report."
            )

        return result, False

    except Exception as e:
        logger.error(f"report_generator failed: {e}")
        return f"Error generating report: {e}", True
