"""Robust optimization builder for OR-Intern v1.0.

Generates Pyomo models for robust optimization with box and ellipsoidal uncertainty sets.
Reformulates robust constraints into tractable deterministic equivalents.
"""

import logging
import re
from pathlib import Path
from typing import Any

from agent.tools._output_dir import get_run_dir
from agent.tools.uncertainty_modeler import (
    UncertaintyModeler,
    UncertaintySet,
    parse_uncertainty_description,
)

logger = logging.getLogger(__name__)


BOX_REFORMULATION_TEMPLATE = '''"""Robust optimization model with box uncertainty.
Generated by OR-Intern v1.0.
Uncertainty set: Box [{lower}, {upper}]
"""

from pyomo.environ import *

model = ConcreteModel()

# ===== Decision Variables =====
{variables}

# ===== Robust Constraints (Deterministic Equivalent) =====
# For box uncertainty: constraint must hold for ALL realizations in the box
# Reformulation: replace uncertain parameter with its worst-case value
{robust_constraints}

# ===== Objective =====
# Worst-case optimization
model.obj = Objective(
    expr={objective},
    sense={sense}
)

# ===== Solve =====
solver = SolverFactory('{solver}')
result = solver.solve(model, tee=False)

# ===== Output =====
print("STATUS:", result.solver.termination_condition)
print("OPTIMAL VALUE:", value(model.obj))
print("WORST-CASE COST:", value(model.obj))
{result_output}
'''

ELLIPSOIDAL_TEMPLATE = '''"""Robust optimization model with ellipsoidal uncertainty.
Generated by OR-Intern v1.0.
Uncertainty set: Ellipsoidal with budget Gamma
"""

from pyomo.environ import *
import numpy as np

model = ConcreteModel()

# ===== Decision Variables =====
{variables}

# ===== Uncertainty Budget (Gamma) =====
# Gamma controls the conservatism: Gamma=0 is nominal, Gamma=sqrt(n) is fully robust
model.Gamma = Param(initialize={gamma})

# ===== Robust Constraints (SOCP Reformulation) =====
# For ellipsoidal uncertainty: reformulated as second-order cone constraint
{robust_constraints}

# ===== Objective =====
model.obj = Objective(
    expr={objective},
    sense={sense}
)

# ===== Solve =====
solver = SolverFactory('{solver}')
result = solver.solve(model, tee=False)

# ===== Output =====
print("STATUS:", result.solver.termination_condition)
print("OPTIMAL VALUE:", value(model.obj))
{result_output}
'''


def _detect_uncertainty_set_type(description: str) -> str:
    """Detect the type of uncertainty set from description."""
    desc_lower = description.lower()

    if "ellipsoid" in desc_lower or "budget" in desc_lower or "gamma" in desc_lower:
        return "ellipsoidal"
    if "box" in desc_lower or "interval" in desc_lower or "[" in desc_lower:
        return "box"
    return "box"


def _extract_bounds(description: str) -> dict[str, tuple[float, float]]:
    """Extract parameter bounds from description."""
    bounds = {}

    interval_pattern = re.compile(
        r"(\w+)\s*(?:in|∈)\s*\[([0-9.]+),\s*([0-9.]+)\]"
    )
    for match in interval_pattern.finditer(description):
        name = match.group(1)
        low = float(match.group(2))
        high = float(match.group(3))
        bounds[name] = (low, high)

    return bounds


def generate_robust_model(
    description: str,
    solver: str = "highs",
    gamma: float = 1.0,
) -> str:
    """Generate a robust optimization model.

    Args:
        description: Problem description with uncertainty information
        solver: Solver to use
        gamma: Budget of uncertainty for ellipsoidal set

    Returns:
        Pyomo model code as string
    """
    set_type = _detect_uncertainty_set_type(description)
    bounds = _extract_bounds(description)

    uncertain_params = parse_uncertainty_description(description)

    var_match = re.findall(r"\b([a-zA-Z_]\w*)\b", description)
    main_vars = []
    for v in var_match:
        if v.lower() not in ("minimize", "maximize", "subject", "to", "where",
                              "robust", "uncertain", "demand", "cost",
                              "the", "and", "or", "in"):
            if v not in main_vars and len(v) <= 5:
                main_vars.append(v)

    if not main_vars:
        main_vars = ["x"]

    lines_vars = []
    for v in main_vars[:5]:
        lines_vars.append(f"model.{v} = Var(domain=NonNegativeReals)")

    lines_con = []
    for v in main_vars[:5]:
        if v in bounds:
            low, high = bounds[v]
            if set_type == "box":
                lines_con.append(f"# Robust constraint for {v}: worst-case at bound")
                lines_con.append(f"# model.robust_{v} = Constraint(expr=model.{v} >= ...)")
            else:
                lines_con.append(f"# Ellipsoidal robust constraint for {v}")

    if not lines_con:
        lines_con.append("# Add robust constraints here")
        lines_con.append("# model.c1 = Constraint(expr=...)")

    obj_expr = " + ".join(f"model.{v}" for v in main_vars[:5])
    if not obj_expr:
        obj_expr = "0"

    result_lines = []
    for v in main_vars[:5]:
        result_lines.append(f"print('  {v} =', value(model.{v}))")

    if set_type == "box":
        lower_str = str(bounds.get(main_vars[0], (0, 100))[0]) if main_vars else "0"
        upper_str = str(bounds.get(main_vars[0], (0, 100))[1]) if main_vars else "100"

        code = BOX_REFORMULATION_TEMPLATE.format(
            lower=lower_str,
            upper=upper_str,
            variables="\n".join(lines_vars),
            robust_constraints="\n".join(lines_con),
            objective=obj_expr,
            sense="minimize",
            solver=solver,
            result_output="\n".join(result_lines),
        )
    else:
        code = ELLIPSOIDAL_TEMPLATE.format(
            gamma=gamma,
            variables="\n".join(lines_vars),
            robust_constraints="\n".join(lines_con),
            objective=obj_expr,
            sense="minimize",
            solver=solver,
            result_output="\n".join(result_lines),
        )

    return code


ROBUST_BUILDER_TOOL_SPEC = {
    "name": "robust_builder",
    "description": (
        "Generate robust optimization models for worst-case optimization under uncertainty. "
        "Supports box and ellipsoidal uncertainty sets with automatic reformulation. "
        "Input: problem description with uncertainty bounds. "
        "Output: Pyomo model code for robust optimization."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "description": {
                "type": "string",
                "description": (
                    "Problem description with uncertainty, e.g. "
                    "'Minimize cost, demand in [100, 200], robust optimization'"
                ),
            },
            "uncertainty_set": {
                "type": "string",
                "enum": ["box", "ellipsoidal"],
                "description": "Uncertainty set type (default: box)",
                "default": "box",
            },
            "gamma": {
                "type": "number",
                "description": "Budget of uncertainty for ellipsoidal set (default: 1.0)",
                "default": 1.0,
            },
            "solver": {
                "type": "string",
                "description": "Solver to use (default: highs)",
                "default": "highs",
            },
        },
        "required": ["description"],
    },
}


async def robust_builder_handler(args: dict[str, Any]) -> tuple[str, bool]:
    """Handler for robust_builder tool."""
    description = args.get("description", "")
    uncertainty_set = args.get("uncertainty_set", "box")
    gamma = args.get("gamma", 1.0)
    solver = args.get("solver", "highs")

    if not description:
        return "Error: No problem description provided", True

    try:
        code = generate_robust_model(description, solver, gamma)

        rundir = get_run_dir()
        model_file = rundir / "model_robust.py"
        model_file.write_text(code, encoding="utf-8")

        bounds = _extract_bounds(description)

        result = (
            f"## Robust Optimization Model Generated\n\n"
            f"**Type**: Robust optimization\n"
            f"**Uncertainty Set**: {uncertainty_set}\n"
            f"**Uncertain Parameters**: {', '.join(bounds.keys()) or 'N/A'}\n"
        )

        if uncertainty_set == "ellipsoidal":
            result += f"**Budget (Gamma)**: {gamma}\n"

        result += (
            f"**Solver**: {solver}\n"
            f"**Model file**: {model_file}\n\n"
            f"### Next Steps\n\n"
            f"1. Review the generated model code\n"
            f"2. Customize robust constraints as needed\n"
            f"3. Run with `solve_job` to solve the robust problem\n"
        )

        return result, False

    except Exception as e:
        logger.error(f"robust_builder failed: {e}")
        return f"Error building robust model: {e}", True
