"""sensitivity_analysis tool for OR-Intern Phase 2.

Extracts dual values, performs parametric analysis on objective coefficients
and constraint right-hand sides, and reports sensitivity ranges.
"""

import asyncio
import logging
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ── Sensitivity analysis via Pyomo ──

_SENSITIVITY_SCRIPT_TEMPLATE = '''\
"""Sensitivity analysis script — auto-generated by OR-Intern."""
import sys
sys.path.insert(0, r"{model_dir}")
from pyomo.environ import *

# Rebuild and solve the model
{model_code}

# Add dual suffix
model.dual = Suffix(direction=Suffix.IMPORT)
model.rc = Suffix(direction=Suffix.IMPORT)

solver = SolverFactory("{solver}")
result = solver.solve(model, tee=False)

print("STATUS:", result.solver.termination_condition)
print("OBJECTIVE:", value(model.obj))

# Dual values (shadow prices)
print("\\nDUAL_VALUES:")
for c in model.component_objects(Constraint, active=True):
    for idx in c:
        try:
            dv = model.dual.get(c[idx], None)
            if dv is not None:
                print(f"  {c[idx].name}: {dv}")
        except Exception:
            pass

# Reduced costs
print("\\nREDUCED_COSTS:")
for v in model.component_objects(Var, active=True):
    for idx in v:
        try:
            rc = model.rc.get(v[idx], None)
            if rc is not None:
                print(f"  {v[idx].name}: {rc}")
        except Exception:
            pass

# Parametric analysis: objective coefficients
{parametric_code}

print("\\nSENSITIVITY_COMPLETE")
'''


def _generate_parametric_code(variables: list[str], constraints: list[str],
                               coeff_range: tuple = (-50, 50, 10)) -> str:
    """Generate parametric analysis code."""
    code = [
        '# Parametric analysis: objective coefficients',
        'print("\\nPARAMETRIC_OBJ:")',
    ]
    for vname in variables:
        code.append(f'print(f"  Var {vname}:")')
        code.append(f'original = value(model.{vname})')
        code.append(
            f'for delta in range({coeff_range[0]}, {coeff_range[1]}+1, {coeff_range[2]}):'
        )
        code.append(f'    model.obj.deactivate()')
        code.append(f'    model.obj_{vname}_param = Objective(')
        code.append(f'        expr=model.obj.expr + delta * model.{vname}, sense=model.obj.sense)')
        code.append(f'    try:')
        code.append(f'        solver.solve(model, tee=False)')
        code.append(f'        print(f"    delta={{delta}}: obj={{value(model.obj)}}, {vname}={{value(model.{vname})}}")')
        code.append(f'    except:')
        code.append(f'        print(f"    delta={{delta}}: INFEASIBLE")')
        code.append(f'    model.del_component(f"obj_{vname}_param")')
        code.append(f'    model.obj.activate()')
    return '\n'.join(code)


# ── Tool spec and handler ──

SENSITIVITY_ANALYSIS_TOOL_SPEC = {
    "name": "sensitivity_analysis",
    "description": (
        "Perform sensitivity analysis on a solved optimization model. "
        "Extracts dual values (shadow prices), reduced costs, and runs "
        "parametric analysis on objective coefficients. "
        "Requires a Pyomo model file path."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "model_path": {
                "type": "string",
                "description": "Path to the Pyomo model Python file",
            },
            "solver": {
                "type": "string",
                "description": "Solver (default: highs)",
                "default": "highs",
            },
            "operation": {
                "type": "string",
                "enum": ["dual", "parametric", "full"],
                "description": "Analysis type: dual (shadow prices), parametric, or full",
                "default": "full",
            },
        },
        "required": ["model_path"],
    },
}


async def sensitivity_analysis_handler(args: dict[str, Any]) -> tuple[str, bool]:
    """Handler for sensitivity_analysis tool."""
    model_path = args.get("model_path", "")
    solver_name = args.get("solver", "highs")
    operation = args.get("operation", "full")

    if not model_path:
        return "Error: No model path provided", True

    model_path = Path(model_path)
    if not model_path.exists():
        return f"Error: Model file not found: {model_path}", True

    model_code = model_path.read_text(encoding="utf-8")

    # Extract variable and constraint names for parametric analysis
    var_names = re.findall(r'model\.(\w+)\s*=\s*Var', model_code)
    constr_names = re.findall(r'model\.(\w+)\s*=\s*Constraint', model_code)

    parametric_code = _generate_parametric_code(var_names, constr_names) \
        if operation in ("parametric", "full") else ""

    script = _SENSITIVITY_SCRIPT_TEMPLATE.format(
        model_dir=model_path.parent,
        model_code=model_code,
        solver=solver_name,
        parametric_code=parametric_code,
    )

    tmpdir = Path(tempfile.gettempdir()) / "or-intern"
    tmpdir.mkdir(exist_ok=True)
    script_path = tmpdir / "sensitivity.py"
    script_path.write_text(script, encoding="utf-8")

    try:
        process = await asyncio.create_subprocess_exec(
            sys.executable, str(script_path),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(model_path.parent),
        )
        stdout, stderr = await asyncio.wait_for(
            process.communicate(), timeout=60
        )
        output = stdout.decode("utf-8", errors="replace")

        # Parse results
        dual_values = {}
        reduced_costs = {}
        parametric_results = []
        status = "UNKNOWN"
        objective = None

        section = None
        for line in output.split("\n"):
            line = line.strip()
            if line.startswith("STATUS:"):
                status = line.split(":", 1)[1].strip()
            elif line.startswith("OBJECTIVE:"):
                try:
                    objective = float(line.split(":", 1)[1].strip())
                except ValueError:
                    pass
            elif line == "DUAL_VALUES:":
                section = "dual"
            elif line == "REDUCED_COSTS:":
                section = "rc"
            elif line.startswith("PARAMETRIC_OBJ:") or line == "SENSITIVITY_COMPLETE":
                section = None
            elif section == "dual" and ":" in line:
                parts = line.split(":", 1)
                try:
                    dual_values[parts[0].strip()] = float(parts[1].strip())
                except ValueError:
                    pass
            elif section == "rc" and ":" in line:
                parts = line.split(":", 1)
                try:
                    reduced_costs[parts[0].strip()] = float(parts[1].strip())
                except ValueError:
                    pass
            elif line.startswith("delta=") and section is None:
                parametric_results.append(line)

        # Build result
        result = f"## Sensitivity Analysis\n\n"
        result += f"**Status**: {status}\n"
        if objective is not None:
            result += f"**Objective**: {objective}\n"

        if dual_values:
            result += "\n### Shadow Prices (Dual Values)\n\n"
            result += "| Constraint | Shadow Price |\n|------------|-------------|\n"
            for name, val in sorted(dual_values.items()):
                result += f"| {name} | {val:.4f} |\n"

        if reduced_costs:
            result += "\n### Reduced Costs\n\n"
            result += "| Variable | Reduced Cost |\n|----------|-------------|\n"
            for name, val in sorted(reduced_costs.items()):
                result += f"| {name} | {val:.4f} |\n"

        if parametric_results:
            result += "\n### Parametric Analysis\n\n"
            result += f"(Showing first {min(20, len(parametric_results))} of {len(parametric_results)} results)\n\n"
            for pr in parametric_results[:20]:
                result += f"- {pr}\n"

        if not dual_values and not reduced_costs:
            result += "\n*Note: Full sensitivity analysis requires a solver that supports dual values (e.g., HiGHS).*\n"

        return result, False

    except asyncio.TimeoutError:
        return "Error: Sensitivity analysis timed out", True
    except Exception as e:
        return f"Error: {e}", True
