"""solve_job tool for OR-Intern Phase 1.

Executes optimization solves using Pyomo + HiGHS (or other solvers).
Manages subprocess execution, captures output, and returns solutions.
"""

import asyncio
import logging
import os
import re
import subprocess
import time
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ── Constants ──
DEFAULT_TIMEOUT = 300  # 5 minutes default
MAX_TIMEOUT = 36000    # 10 hours max
PYOMO_SOLVE_SCRIPT_TEMPLATE = """\
# Auto-generated by OR-Intern solve_job
import sys
sys.path.insert(0, r'{model_dir}')

from pyomo.environ import *

# Load and solve the model
{model_content}

# Fallback: if no model_content, exec the model file
if 'model' not in dir() or not isinstance(model, ConcreteModel):
    exec(open(r'{model_path}', encoding='utf-8').read())
"""
PYOMO_SOLVE_SCRIPT_SUFFIX = """\

# Print results
from pyomo.environ import value
print("=" * 50)
print("OR_INTERN_SOLUTION_START")
if result.solver.termination_condition == TerminationCondition.optimal:
    print("STATUS: OPTIMAL")
elif result.solver.termination_condition in (
    TerminationCondition.feasible,
    TerminationCondition.locallyOptimal,
):
    print("STATUS: FEASIBLE")
else:
    print(f"STATUS: {result.solver.termination_condition}")

print(f"OBJECTIVE: {value(model.obj)}")
print("VARIABLES:")
for v in model.component_objects(Var, active=True):
    for index in v:
        try:
            val = value(v[index])
            print(f"  {v[index].name} = {val}")
        except Exception:
            pass
print("OR_INTERN_SOLUTION_END")
print("=" * 50)
"""


def _sanitize_pyomo_code(code: str) -> str:
    """Remove solve/job sections from Pyomo code so solve_job can add its own."""
    # Remove existing SolverFactory/solve sections
    lines = code.split("\n")
    filtered = []
    skip = False
    for line in lines:
        if re.search(r"SolverFactory|\.solve\(|result\s*=", line) and not skip:
            skip = True
            continue
        if skip:
            if line.strip() == "" or re.match(r"print|^\s*$", line):
                continue
            skip = False
        filtered.append(line)
    return "\n".join(filtered)


# ── Tool spec and handler ──

SOLVE_JOB_TOOL_SPEC = {
    "name": "solve_job",
    "description": (
        "Execute an optimization solve using Pyomo and a specified solver. "
        "The model file should be a valid Pyomo Python script. "
        "Operations: 'run' (execute solve), 'status' (check if solver is available). "
        "Returns the solution status, objective value, and variable values."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "operation": {
                "type": "string",
                "enum": ["run", "status"],
                "description": "Operation: 'run' to execute solve, 'status' to check solver availability",
                "default": "run",
            },
            "model_path": {
                "type": "string",
                "description": "Path to the Pyomo model Python file",
            },
            "solver": {
                "type": "string",
                "description": "Solver to use (default: highs)",
                "default": "highs",
            },
            "timeout": {
                "type": "integer",
                "description": f"Maximum solve time in seconds (default: {DEFAULT_TIMEOUT})",
                "default": DEFAULT_TIMEOUT,
            },
        },
    },
}


async def solve_job_handler(args: dict[str, Any]) -> tuple[str, bool]:
    """Handler for solve_job tool."""
    operation = args.get("operation", "run")

    if operation == "status":
        solvers = []
        for name in ["highs", "scip", "glpk", "gurobi", "cplex"]:
            try:
                from pyomo.environ import SolverFactory
                s = SolverFactory(name)
                if s.available():
                    solvers.append(f"✅ {name}")
                else:
                    solvers.append(f"❌ {name} (not available)")
            except Exception:
                solvers.append(f"❌ {name} (not found)")
        return "## Solver Status\n\n" + "\n".join(solvers), False

    # Run solve
    model_path = args.get("model_path", "")
    solver_name = args.get("solver", "highs")
    timeout = args.get("timeout", DEFAULT_TIMEOUT)

    if not model_path:
        return "Error: No model path provided", True

    model_path = Path(model_path)
    if not model_path.exists():
        return f"Error: Model file not found: {model_path}", True

    # Read model code
    model_code = model_path.read_text(encoding="utf-8")

    # OR-Intern: Run the model file directly (it's a complete Pyomo script)
    # No sanitization needed — the model file IS the solve script
    t0 = time.monotonic()

    try:
        # Use the same Python interpreter that's running OR-Intern
        import sys
        python_exe = sys.executable

        # Execute the model file directly
        process = await asyncio.create_subprocess_exec(
            python_exe,
            str(model_path),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(model_path.parent),
        )

        stdout, stderr = await asyncio.wait_for(
            process.communicate(), timeout=min(timeout, MAX_TIMEOUT)
        )

        elapsed = time.monotonic() - t0
        stdout_str = stdout.decode("utf-8", errors="replace")
        stderr_str = stderr.decode("utf-8", errors="replace")

        if process.returncode != 0:
            error_msg = (
                f"## Solve Failed (exit code {process.returncode})\n\n"
                f"**Time**: {elapsed:.1f}s\n\n"
                f"**Error output**:\n```\n{stderr_str[-2000:]}\n```\n\n"
                f"**Stdout tail**:\n```\n{stdout_str[-1000:]}\n```"
            )
            return error_msg, True

        # Parse solution
        solution = _parse_solution(stdout_str)

        if solution["status"] == "UNKNOWN":
            partial_result = (
                f"## Solve Completed (status unclear)\n\n"
                f"**Time**: {elapsed:.1f}s\n"
                f"**Exit code**: {process.returncode}\n\n"
                f"**Output**:\n```\n{stdout_str[-2000:]}\n```"
            )
            return partial_result, False

        result = (
            f"## Solve Results\n\n"
            f"**Status**: {solution['status']}\n"
            f"**Solver**: {solver_name}\n"
            f"**Time**: {elapsed:.1f}s\n"
        )

        if solution.get("objective") is not None:
            result += f"**Objective value**: {solution['objective']}\n"

        if solution.get("variables"):
            result += "\n**Variable values**:\n"
            for name, val in sorted(solution["variables"].items()):
                result += f"  - {name} = {val}\n"

        if stderr_str.strip():
            # Show last few solver log lines
            log_lines = [l for l in stderr_str.split("\n") if l.strip()][-5:]
            if log_lines:
                result += f"\n**Solver log**:\n```\n" + "\n".join(log_lines) + "\n```\n"

        return result, False

    except asyncio.TimeoutError:
        elapsed = time.monotonic() - t0
        try:
            process.kill()
        except Exception:
            pass
        return (
            f"## Solve Timed Out\n\n"
            f"**Time limit**: {timeout}s\n"
            f"**Elapsed**: {elapsed:.1f}s\n"
            f"Try increasing the timeout or simplifying the model.",
            True
        )


def _parse_solution(output: str) -> dict:
    """Parse the OR_INTERN_SOLUTION markers from solve output."""
    solution = {"status": "UNKNOWN", "objective": None, "variables": {}}

    # Check for solution markers
    if "OR_INTERN_SOLUTION_START" in output:
        section = output.split("OR_INTERN_SOLUTION_START")[1]
        section = section.split("OR_INTERN_SOLUTION_END")[0]
    else:
        section = output  # Parse the whole output

    # Parse Pyomo output format: "  x = 10.0" or "STATUS: optimal"
    for line in section.split("\n"):
        line = line.strip()
        if re.match(r"(?:STATUS|Status):", line, re.IGNORECASE):
            solution["status"] = line.split(":", 1)[1].strip().upper()
        elif re.match(r"(?:OBJECTIVE|Objective):", line, re.IGNORECASE):
            try:
                solution["objective"] = float(line.split(":", 1)[1].strip())
            except ValueError:
                pass
        elif "=" in line and not any(kw in line.lower() for kw in ["status", "objective", "solve", "termination"]):
            parts = line.split("=", 1)
            name = parts[0].strip()
            try:
                val = float(parts[1].strip())
                solution["variables"][name] = val
            except ValueError:
                pass

    return solution
