"""Stochastic programming builder for OR-Intern v1.0.

Generates Pyomo models for two-stage and multi-stage stochastic programming.
Uses Sample Average Approximation (SAA) for scenario-based optimization.
"""

import logging
import re
from pathlib import Path
from typing import Any

from agent.tools._output_dir import get_run_dir
from agent.tools.uncertainty_modeler import (
    UncertaintyModeler,
    parse_uncertainty_description,
)

logger = logging.getLogger(__name__)


TWO_STAGE_TEMPLATE = '''"""Two-stage stochastic programming model.
Generated by OR-Intern v1.0.
Scenarios: {n_scenarios}
"""

from pyomo.environ import *
import numpy as np

np.random.seed(42)

# ===== Scenario Data =====
n_scenarios = {n_scenarios}
scenario_data = {scenario_data}

model = ConcreteModel()

# ===== First-Stage Decision Variables =====
{first_stage_vars}

# ===== Second-Stage Decision Variables (per scenario) =====
model.scenarios = RangeSet(n_scenarios)
{second_stage_vars}

# ===== First-Stage Constraints =====
{first_stage_constraints}

# ===== Second-Stage Constraints (scenario-dependent) =====
{second_stage_constraints}

# ===== Objective: Minimize Expected Cost =====
# E[first_stage_cost + second_stage_cost]
model.obj = Objective(
    expr={first_stage_cost} + 
    (1.0 / n_scenarios) * sum(
        {second_stage_cost_expr} for s in model.scenarios
    ),
    sense=minimize
)

# ===== Solve =====
solver = SolverFactory('{solver}')
result = solver.solve(model, tee=False)

# ===== Output =====
print("STATUS:", result.solver.termination_condition)
print("OPTIMAL VALUE:", value(model.obj))
print("EXPECTED COST:", value(model.obj))
{result_output}
'''


def _extract_problem_structure(description: str) -> dict[str, Any]:
    """Extract problem structure from natural language description."""
    structure = {
        "first_stage_vars": [],
        "second_stage_vars": [],
        "uncertain_params": [],
        "first_stage_cost": "",
        "second_stage_cost": "",
    }

    first_match = re.search(
        r"first.stage\s*[:\-]?\s*(.+?)(?:second.stage|uncertain|$)",
        description, re.I | re.DOTALL,
    )
    if first_match:
        structure["first_stage_text"] = first_match.group(1).strip()

    second_match = re.search(
        r"second.stage\s*[:\-]?\s*(.+?)(?:uncertain|$)",
        description, re.I | re.DOTALL,
    )
    if second_match:
        structure["second_stage_text"] = second_match.group(1).strip()

    return structure


def generate_stochastic_model(
    description: str,
    n_scenarios: int = 100,
    solver: str = "highs",
    seed: int = 42,
) -> str:
    """Generate a two-stage stochastic programming model.

    Args:
        description: Problem description with uncertainty information
        n_scenarios: Number of scenarios for SAA
        solver: Solver to use
        seed: Random seed for reproducibility

    Returns:
        Pyomo model code as string
    """
    modeler = UncertaintyModeler(seed=seed)

    uncertain_params = parse_uncertainty_description(description)
    for name, params in uncertain_params.items():
        modeler.define_parameter(
            name=name,
            distribution=params["distribution"],
            **{k: v for k, v in params.items() if k != "distribution"},
        )

    scenarios = modeler.generate_scenario_matrix(n_scenarios)

    scenario_data_str = "{\n"
    for name, values in scenarios.items():
        scenario_data_str += f"    '{name}': {values.tolist()},\n"
    scenario_data_str += "}"

    lines_first_var = []
    lines_second_var = []
    lines_first_con = []
    lines_second_con = []

    var_match = re.findall(r"\b([a-zA-Z_]\w*)\b", description)
    main_vars = []
    for v in var_match:
        if v.lower() not in ("minimize", "maximize", "subject", "to", "where",
                              "first", "stage", "second", "uncertain", "demand",
                              "cost", "capacity", "the", "and", "or"):
            if v not in main_vars and len(v) <= 5:
                main_vars.append(v)

    if not main_vars:
        main_vars = ["x", "y"]

    for v in main_vars[:3]:
        lines_first_var.append(f"model.{v} = Var(domain=NonNegativeReals)")

    for v in main_vars[:3]:
        lines_second_var.append(
            f"model.{v}_recourse = Var(model.scenarios, domain=NonNegativeReals)"
        )

    lines_first_con.append("model.budget = Constraint(")
    lines_first_con.append(f"    expr={'+'.join(f'model.{v}' for v in main_vars[:3])} <= 100")
    lines_first_con.append(")")

    for v in main_vars[:3]:
        lines_second_con.append(f"# Recourse constraints for {v}")
        lines_second_con.append(f"# model.recourse_{v} = Constraint(model.scenarios, ...)")

    first_stage_cost = " + ".join(f"model.{v}" for v in main_vars[:3])
    if not first_stage_cost:
        first_stage_cost = "0"

    second_stage_cost_parts = []
    for v in main_vars[:3]:
        if v in uncertain_params:
            second_stage_cost_parts.append(
                f"scenario_data['{v}'][s-1] * model.{v}_recourse[s]"
            )
        else:
            second_stage_cost_parts.append(f"model.{v}_recourse[s]")
    second_stage_cost_expr = " + ".join(second_stage_cost_parts)
    if not second_stage_cost_expr:
        second_stage_cost_expr = "0"

    result_lines = []
    for v in main_vars[:3]:
        result_lines.append(f"print('  {v} =', value(model.{v}))")

    code = TWO_STAGE_TEMPLATE.format(
        n_scenarios=n_scenarios,
        scenario_data=scenario_data_str,
        first_stage_vars="\n".join(lines_first_var),
        second_stage_vars="\n".join(lines_second_var),
        first_stage_constraints="\n".join(lines_first_con),
        second_stage_constraints="\n".join(lines_second_con),
        first_stage_cost=first_stage_cost,
        second_stage_cost_expr=second_stage_cost_expr,
        solver=solver,
        result_output="\n".join(result_lines),
    )

    return code


STOCHASTIC_BUILDER_TOOL_SPEC = {
    "name": "stochastic_builder",
    "description": (
        "Generate stochastic programming models for optimization under uncertainty. "
        "Supports two-stage stochastic programming with Sample Average Approximation. "
        "Input: problem description with uncertainty information. "
        "Output: Pyomo model code for stochastic optimization."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "description": {
                "type": "string",
                "description": (
                    "Problem description with uncertainty, e.g. "
                    "'Minimize cost, demand in [100, 200] is uncertain'"
                ),
            },
            "n_scenarios": {
                "type": "integer",
                "description": "Number of scenarios (default: 100)",
                "default": 100,
            },
            "solver": {
                "type": "string",
                "description": "Solver to use (default: highs)",
                "default": "highs",
            },
        },
        "required": ["description"],
    },
}


async def stochastic_builder_handler(args: dict[str, Any]) -> tuple[str, bool]:
    """Handler for stochastic_builder tool."""
    description = args.get("description", "")
    n_scenarios = args.get("n_scenarios", 100)
    solver = args.get("solver", "highs")

    if not description:
        return "Error: No problem description provided", True

    try:
        code = generate_stochastic_model(description, n_scenarios, solver)

        rundir = get_run_dir()
        model_file = rundir / "model_stochastic.py"
        model_file.write_text(code, encoding="utf-8")

        uncertain_params = parse_uncertainty_description(description)

        result = (
            f"## Stochastic Programming Model Generated\n\n"
            f"**Type**: Two-stage stochastic programming\n"
            f"**Scenarios**: {n_scenarios}\n"
            f"**Uncertain Parameters**: {', '.join(uncertain_params.keys()) or 'N/A'}\n"
            f"**Solver**: {solver}\n"
            f"**Model file**: {model_file}\n\n"
            f"### Next Steps\n\n"
            f"1. Review the generated model code\n"
            f"2. Customize recourse constraints as needed\n"
            f"3. Run with `solve_job` to solve the stochastic program\n"
        )

        return result, False

    except Exception as e:
        logger.error(f"stochastic_builder failed: {e}")
        return f"Error building stochastic model: {e}", True
