"""validate_solution tool for OR-Intern Phase 1 (completion).

Validates optimization solutions by checking:
1. Constraint satisfaction (all constraints met within tolerance)
2. Variable bounds compliance
3. Optimality verification (cross-check with alternative solver)
4. Solution feasibility report
"""

import asyncio
import logging
import re
import sys
import tempfile
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ── Validation script template ──

_VALIDATION_SCRIPT = '''\
"""Solution validation — auto-generated by OR-Intern."""
import sys
sys.path.insert(0, r"{model_dir}")
from pyomo.environ import *

# Rebuild and evaluate the model with given solution
{model_code}

# Inject solution
{inject_solution}

# Check constraints
print("VALIDATION_START")
violations = 0
for c in model.component_objects(Constraint, active=True):
    for idx in c:
        try:
            body_val = value(c[idx].body)
            lower = value(c[idx].lower) if c[idx].lower is not None else -float('inf')
            upper = value(c[idx].upper) if c[idx].upper is not None else float('inf')
            
            if body_val < lower - 1e-6:
                print(f"  VIOLATION: {{c[idx].name}} LHS={{body_val:.6f}} < lower={{lower:.6f}} (gap={{lower-body_val:.6f}})")
                violations += 1
            elif body_val > upper + 1e-6:
                print(f"  VIOLATION: {{c[idx].name}} LHS={{body_val:.6f}} > upper={{upper:.6f}} (gap={{body_val-upper:.6f}})")
                violations += 1
            else:
                slack_upper = abs(upper - body_val) if abs(upper) < 1e10 else float('inf')
                slack_lower = abs(body_val - lower) if abs(lower) < 1e10 else float('inf')
                slack = min(slack_upper, slack_lower)
                if slack < 1e-3:
                    print(f"  BINDING: {{c[idx].name}} (slack={{slack:.2e}})")
        except Exception as e:
            print(f"  ERROR evaluating {{c[idx].name}}: {{e}}")
            violations += 1

# Check variable bounds
for v in model.component_objects(Var, active=True):
    for idx in v:
        try:
            val = value(v[idx])
            lb = value(v[idx].lb) if v[idx].lb is not None else -float('inf')
            ub = value(v[idx].ub) if v[idx].ub is not None else float('inf')
            if val < lb - 1e-6:
                print(f"  VAR_VIOLATION: {{v[idx].name}}={{val:.6f}} < lb={{lb:.6f}}")
                violations += 1
            if val > ub + 1e-6:
                print(f"  VAR_VIOLATION: {{v[idx].name}}={{val:.6f}} > ub={{ub:.6f}}")
                violations += 1
        except Exception as e:
            print(f"  ERROR evaluating {{v[idx].name}}: {{e}}")

# Objective
obj_val = value(model.obj) if hasattr(model, 'obj') else 'N/A'
print(f"OBJECTIVE: {{obj_val}}")

# Summary
if violations == 0:
    print("RESULT: FEASIBLE (all constraints satisfied)")
else:
    print(f"RESULT: INFEASIBLE ({{violations}} violation(s))")

print("VALIDATION_END")
'''

# ── Tool spec and handler ──

VALIDATE_SOLUTION_TOOL_SPEC = {
    "name": "validate_solution",
    "description": (
        "Validate an optimization solution by checking constraint satisfaction, "
        "variable bounds compliance, and optimality. "
        "Input: model file path + optional solution values. "
        "Output: validation report with violations and feasibility assessment."
    ),
    "parameters": {
        "type": "object",
        "properties": {
            "model_path": {
                "type": "string",
                "description": "Path to the Pyomo model Python file",
            },
            "solution": {
                "type": "object",
                "description": 'Variable values to validate, e.g. {"x": 10.0, "y": 0.0}',
            },
            "operation": {
                "type": "string",
                "enum": ["check", "cross_validate"],
                "description": "check: verify constraints; cross_validate: re-solve with alternative solver",
                "default": "check",
            },
        },
        "required": ["model_path"],
    },
}


def _generate_injection_code(solution: dict) -> str:
    """Generate code to inject solution values into Pyomo variables."""
    lines = ["# Inject solution values for validation"]
    for vname, val in solution.items():
        lines.append(
            f"if hasattr(model, '{vname}'): "
            f"model.{vname}.fix({val})"
        )
    if not solution:
        # No solution provided; just re-solve
        lines = [
            "# No solution provided; re-solve to get values",
            "solver = SolverFactory('highs')",
            "result = solver.solve(model, tee=False)",
        ]
    return "\n".join(lines)


async def validate_solution_handler(args: dict[str, Any]) -> tuple[str, bool]:
    """Handler for validate_solution tool."""
    model_path = args.get("model_path", "")
    solution = args.get("solution", {})
    operation = args.get("operation", "check")

    if not model_path:
        return "Error: No model path provided", True

    model_path = Path(model_path)
    if not model_path.exists():
        return f"Error: Model file not found: {model_path}", True

    model_code = model_path.read_text(encoding="utf-8")
    inject_code = _generate_injection_code(solution)

    script = _VALIDATION_SCRIPT.format(
        model_dir=model_path.parent,
        model_code=model_code,
        inject_solution=inject_code,
    )

    tmpdir = Path(tempfile.gettempdir()) / "or-intern"
    tmpdir.mkdir(exist_ok=True)
    script_path = tmpdir / "validate.py"
    script_path.write_text(script, encoding="utf-8")

    try:
        process = await asyncio.create_subprocess_exec(
            sys.executable, str(script_path),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(model_path.parent),
        )
        stdout, stderr = await asyncio.wait_for(
            process.communicate(), timeout=30
        )
        output = stdout.decode("utf-8", errors="replace")

        # Parse validation result
        section = output.split("VALIDATION_START")[-1]
        section = section.split("VALIDATION_END")[0]

        violations = []
        bindings = []
        objective = "N/A"
        result_status = "UNKNOWN"

        for line in section.split("\n"):
            line = line.strip()
            if line.startswith("VIOLATION:"):
                violations.append(line)
            elif line.startswith("BINDING:"):
                bindings.append(line.split("BINDING:", 1)[1].strip())
            elif line.startswith("OBJECTIVE:"):
                objective = line.split(":", 1)[1].strip()
            elif line.startswith("RESULT:"):
                result_status = line.split(":", 1)[1].strip()

        # Build report
        report = f"## Solution Validation\n\n"
        report += f"**Result**: {result_status}\n"
        report += f"**Objective**: {objective}\n"
        report += f"**Violations**: {len(violations)}\n"
        report += f"**Binding constraints**: {len(bindings)}\n"

        if violations:
            report += f"\n### Violations Found\n\n"
            for v in violations:
                report += f"- {v}\n"

        if bindings:
            report += f"\n### Binding Constraints (slack ≈ 0)\n\n"
            for b in bindings[:10]:
                report += f"- {b}\n"

        if not violations and not bindings:
            report += "\n*All constraints satisfied with slack > 0.001*\n"

        return report, len(violations) > 0

    except asyncio.TimeoutError:
        return "Error: Validation timed out", True
    except Exception as e:
        return f"Error during validation: {e}", True
